library(glmmTMB)
library(performance)
library(jtools)
data<-read.csv("data.csv")

mod1<-glmmTMB(betas.LCBD~River.dist.lake* (1|O.NET),family=beta_family(), data=data)
mod2<-glmmTMB(betas.LCBD~Head.river.dist* (1|O.NET),family=beta_family(),data=data)
mod3<-glmmTMB(betas.LCBD~Head.river.dist*River.dist.lake* (1|O.NET),family=beta_family(),data=data)
null<-glmmTMB(betas.LCBD~1* (1|O.NET),family=beta_family(),data=data)

mod1<-glmmTMB(betas.LCBD~River.dist.lake+ (1|O.NET),family=gaussian(), data=dd_specie)
mod2<-glmmTMB(betas.LCBD~Head.river.dist+ (1|O.NET),family=gaussian(),data=dd_specie)
mod3<-glmmTMB(betas.LCBD~Head.river.dist*River.dist.lake+ (1|O.NET),family=gaussian(),data=dd_specie)
null<-glmmTMB(betas.LCBD~1+ (1|O.NET),family=gaussian(),data=dd_specie)

mod1<-lmer(betas.LCBD~River.dist.lake+ (1|O.NET), data=dd_specie)
mod2<-lmer(betas.LCBD~Head.river.dist+ (1|O.NET),data=dd_specie)
mod3<-lmer(betas.LCBD~Head.river.dist*River.dist.lake+ (1|O.NET),data=dd_specie)
null<-lmer(betas.LCBD~1+ (1|O.NET),data=dd_specie)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3,null,weights = TRUE, sort = FALSE)

VarCorr.merMod(mod3)
summary.merMod(mod1)
summary(mod3)
performance::r2(mod1)
performance::r2(mod2)
performance::r2(mod3)
performance::r2(null)

mod1<-glmmTMB(N1~River.dist.lake+ (1|O.NET),family=gaussian(), data=data)
mod2<-glmmTMB(N1~Head.river.dist+ (1|O.NET),family=gaussian(),data=data)
mod3<-glmmTMB(N1~River.dist.lake*Head.river.dist+ (1|O.NET),family=gaussian(),data=data)
null<-glmmTMB(N1~1+ (1|O.NET),family=gaussian(),data=data)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3, null,weights = TRUE, sort = F)

performance::r2(mod1)
performance::r2(mod2)
performance::r2(mod3)
performance::r2(null)


###TEC

################################################################################################################
#GLMM's
devtools::install_github('bcjaeger/r2glmm')
r2glmm::Glimmix_R2_V3(mod1)

mod1<-glmmTMB(betas.LCBD~Spatial+ (1|O.NET),family=beta_family(), data=all_big_dat)
mod2<-glmmTMB(betas.LCBD~E_PC1+ (1|O.NET),family=beta_family(),data=all_big_dat)
mod3<-glmmTMB(betas.LCBD~Com.Size.Gradient+ (1|O.NET),family=beta_family(),data=all_big_dat)
mod4<-glmmTMB(betas.LCBD~Spatial*E_PC1+ (1|O.NET),family=beta_family(),data=all_big_dat)
mod5<-glmmTMB(betas.LCBD~Spatial*Com.Size.Gradient+ (1|O.NET),family=beta_family(), data=all_big_dat)
mod6<-glmmTMB(betas.LCBD~E_PC1*Com.Size.Gradient+ (1|O.NET),family=beta_family(), data=all_big_dat)
mod7<-glmmTMB(betas.LCBD~E_PC1*Com.Size.Gradient*Spatial+ (1|O.NET),family=beta_family(),data=all_big_dat)
null<-glmmTMB(betas.LCBD~ (1|O.NET),family=beta_family(),data=all_big_dat)

mod1<-glmmTMB(betas.LCBD~Spatial+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod2<-glmmTMB(betas.LCBD~E_PC1+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod3<-glmmTMB(betas.LCBD~Com.Size.Gradient+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod4<-glmmTMB(betas.LCBD~Spatial*E_PC1+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod5<-glmmTMB(betas.LCBD~Spatial*Com.Size.Gradient+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod6<-glmmTMB(betas.LCBD~E_PC1*Com.Size.Gradient+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod7<-glmmTMB(betas.LCBD~E_PC1*Com.Size.Gradient*Spatial+ (1|O.NET),family=gaussian(),data=all_big_dat)
null<-glmmTMB(betas.LCBD~ (1|O.NET),family=gaussian(),data=all_big_dat)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3,mod4,mod5,mod6, null,weights = TRUE, sort = FALSE)
r2(mod1)
r2(mod2)
r2(mod3)
r2(mod4)
r2(mod5)
r2(mod6)
r2(null)
r2(mod3,tolerance = 1e-10)
summary(mod1)
insight::compute_variances(mod1)
fixef(mod6)
VarCorr(mod6)
r.squaredGLMM(null)
AIC(mod4)
performance::r2(mod1)
performance::r2_nakagawa(mod1,tolerance = 1e-12)
performance::r2_tjur(mod1)
performance::r2_mckelvey(mod1)
performance::r2_nagelkerke(mod1)
insight::get_variance(mod1)
performance::r2_zeroinflated(mod1)
r2_nakagawa(mod7)
performance::check_singularity(mod1,tolerance = 1e-10)

mod1<-glmmTMB(N1~Spatial+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod2<-glmmTMB(N1~E_PC1+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod3<-glmmTMB(N1~Com.Size.Gradient+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod4<-glmmTMB(N1~Spatial*E_PC1+ (1|O.NET),family=gaussian(),data=all_big_dat)
mod5<-glmmTMB(N1~Spatial*Com.Size.Gradient+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod6<-glmmTMB(N1~E_PC1*Com.Size.Gradient+ (1|O.NET),family=gaussian(), data=all_big_dat)
mod7<-glmmTMB(N1~E_PC1*Com.Size.Gradient*Spatial+ (1|O.NET),family=gaussian(),data=all_big_dat)
null<-glmmTMB(N1~ 1+(1|O.NET),family=gaussian(),data=all_big_dat)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3,mod4,mod5,mod6, null,weights = TRUE, sort = F)
summary(mod1)
r2(mod1)
fixef(mod6)
VarCorr(mod6)
r.squaredGLMM(mod7)
AIC(mod6)
performance::r2(mod6)

levels(all_big_dat$O.NET)
levels(dd_specie$O.NET)

all_big_dat$O.NET<-as.factor(all_big_dat$O.NET)
dd_specie$O.NET<-as.factor(dd_specie$O.NET)
